NDefines.NAir.AIR_WING_XP_TRAINING_MISSION_GAIN_DAILY = 14.0 -- Vanilla 7.0 x2
NDefines.NCountry.AIR_SUPPLY_CONVERSION_SCALE = 0.05 -- Vanilla 0.01 x5
NDefines.NMilitary.COMBAT_SUPPLY_LACK_ATTACKER_ATTACK = -0.02 -- Vanilla -0.25
NDefines.NMilitary.COMBAT_SUPPLY_LACK_ATTACKER_DEFEND = -0.02 -- Vanilla -0.65
NDefines.NMilitary.COMBAT_SUPPLY_LACK_DEFENDER_ATTACK = -0.02 -- Vanilla -0.35
NDefines.NMilitary.COMBAT_SUPPLY_LACK_DEFENDER_DEFEND = -0.02 -- Vanilla -0.15
NDefines.NMilitary.COMBAT_REINFORCE_CHANCE = 0.50
NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY = -0.75 -- Vanilla -1
NDefines.NMilitary.COMBAT_OVER_WIDTH_PENALTY_MAX = -0.45 -- Vanilla -0.33
NDefines.NNavy.DOMINANCE_CONTROLLED_THRESHOLD_RATIO = 0.10 -- Vanilla 0.60
NDefines.NNavy.DOMINANCE_DAILY_GAIN_FACTOR = 0.04 -- Vanilla 0.02
NDefines.NNavy.DOMINANCE_DAILY_LOSS_FACTOR = 0.03 -- Vanilla 0.04
NDefines.NNavy.NAVAL_DOMINANCE_STRIKE_FORCE_FRACTION = 0.0006 -- Vanilla 0.0006
NDefines.NNavy.NAVAL_DOMINANCE_ORG_RECOVERY = 0.20 -- Vanilla 0.10
NDefines.NNavy.NAVAL_DOMINANCE_SHIP_RECOVERY_CHANCE = 0.25 -- Vanilla 0.10
NDefines.NNavy.AIR_BASE_DOMINANCE_FACTOR = 0.005 -- Vanilla 0.02
NDefines.NNavy.RADAR_DOMINANCE_FACTOR = 0.01 -- Vanilla 0.05
NDefines.NNavy.NAVAL_BASE_DOMINANCE_FACTOR = 0.003 -- Vanilla 0.01
NDefines.NNavy.NAVAL_HOMEBASE_OWNERSHIP_BONUS = 0.01 -- Vanilla 0.04
NDefines.NIntel.NAVAL_DOMINANCE_INTEL_LOW = 0.25 -- Vanilla 0.4
NDefines.NIntel.NAVAL_DOMINANCE_INTEL_LOW_DOMINANCE_PENALTY_START = 0.05 -- Vanilla 0.1
NDefines.NIntel.NAVAL_DOMINANCE_INTEL_LOW_DOMINANCE_MIN_PENALTY = 0.80 -- Vanilla 0.5
NDefines.NAir.DETECT_CHANCE_FROM_OCCUPATION = 0.05 -- Vanilla 0.10
NDefines.NAir.DETECT_CHANCE_FROM_RADARS = 0.15 -- Vanilla 0.5
NDefines.NAir.DETECT_CHANCE_FROM_AIRCRAFTS = 0.80 -- Vanilla 0.8
NDefines.NAir.COMBAT_BETTER_AGILITY_DAMAGE_REDUCTION = 0.75 -- Vanilla 0.45
NDefines.NNavy.SHIP_SUPPORT_NEED_FACTOR = 0.02 -- Vanilla 0.1
NDefines.NNavy.CONVOY_BLOCKED_BY_ENEMY_CONTROLLED_REGION = false -- Vanilla true
NDefines.NNavy.MISSION_DOMINANCE_RATIOS = { -- dominance multipliers for different mission types
	0.0, -- HOLD
	1.5, -- PATROL
	0.8, -- STRIKE FORCE
	0.5, -- CONVOY RAIDING
	0.7, -- CONVOY ESCORT
	0.3, -- MINES PLANTING
	0.3, -- MINES SWEEPING
	0.0, -- TRAIN
	0.0, -- RESERVE_FLEET
	2.0, -- NAVAL_INVASION_SUPPORT
}